name: Test
on:
  workflow_dispatch:
    inputs:
      param1:
        type: string
        required: true

permissions:
  contents: write
  pull-requests: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create rebuild workflow
        uses: ./
